[project]
name = "minihack-remdm-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=1.8.0",
    "matplotlib>=3.10.8",
    "minihack>=1.0.2",
    "numpy>=2.4.4",
    "orjson>=3.11.8",
    "polars>=1.39.3",
    "pyyaml>=6.0.3",
    "scipy>=1.17.1",
    "torch>=2.11.0",
    "wandb>=0.25.1",
]
